seed_everything: 0
model:
  class_path: models.template_model.TemplateNet
  init_args:
    experiment_directory: ./experiments/default_experiment
data:
  class_path: data.template_datamodule.TemplateDataModule
  init_args:
    train_batch_size: 1
    test_batch_size: 1
    train_num_workers: 1
    test_num_workers: 1
    train_val_split: 0.8
ckpt_path: null
trainer:
  logger: true
  enable_checkpointing: true
  default_root_dir: ${model.init_args.experiment_directory}/
  gradient_clip_val: null
  gradient_clip_algorithm: null
  process_position: 0
  num_nodes: 1
  num_processes: 1
  devices: 1
  auto_select_gpus: false
  tpu_cores: null
  ipus: null
  log_gpu_memory: null
  progress_bar_refresh_rate: null
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1
  fast_dev_run: false
  accumulate_grad_batches: null
  max_epochs: null
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 1.0
  flush_logs_every_n_steps: null
  log_every_n_steps: 50
  accelerator: gpu
  strategy: null
  sync_batchnorm: true
  precision: 32
  enable_model_summary: true
  weights_summary: top
  weights_save_path: null
  num_sanity_val_steps: 2
  resume_from_checkpoint: null
  profiler: null
  benchmark: false
  deterministic: false
  reload_dataloaders_every_n_epochs: 0
  reload_dataloaders_every_epoch: false
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  prepare_data_per_node: null
  plugins: null
  amp_backend: native
  amp_level: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  stochastic_weight_avg: false
  terminate_on_nan: null
  callbacks:
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args: 
        logging_interval: step
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args: 
        dirpath: ${model.init_args.experiment_directory}/checkpoints/
        monitor: val/loss
        filename: epoch{epoch:03d}-val_loss{val/loss:.6f}
        auto_insert_metric_name: false
        save_top_k: 5
        save_last: true
